name: Request new vocabulary term.

description: Add metadata about a new vocabulary term.

title: Add vocabulary term [X]

labels: [ New, VocabularyTerm ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new vocabulary term request form!

        Please provide the necessary details about the vocabulary term, including its unique identifier, name, description, and relevant hierarchy information.
  
  - type: input
    id: id
    attributes:
      label: vocabulary term URI
      description: Unique resource identifier for the vocabulary term.
      placeholder: ex. peh:MA-0012abxy74
    validations:
      required: true

  - type: input
    id: unique_name
    attributes:
      label: Unique Name
      description: A unique, human-readable name for the vocabulary term.
      placeholder: ex. example_vocabulary_term
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Name
      description: The official name of the vocabulary term.
      placeholder: ex. Example vocabulary term
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief description of the vocabulary term.
    validations:
      required: false

  - type: input
    id: label
    attributes:
      label: Label
      description: A concise label for the vocabulary term.
      placeholder: ex. Example Label
    validations:
      required: false

  - type: textarea
    id: remark
    attributes:
      label: Remark
      description: Any additional notes or remarks regarding the vocabulary term.
    validations:
      required: false


  - type: textarea
    id: translations
    attributes:
      label: Translations
      description: |
        Provide translations as a list in the format:
        ```
        - property_name: example_property
          language: en
          translated_value: Example Translation
        - property_name: another_property
          language: fr
          translated_value: Traduction Exemple
        ```
      placeholder: |
        - property_name: vocabulary term_property
          language: en
          translated_value: Example Translation
    validations:
      required: false
