name: Publish Vocabulary

permissions:
  contents: write

on:
    pull_request:
    release:
        types: [published]


jobs:
    publish-vocabulary:
        if: github.repository != 'eu-parc/vocabulary-template'
        uses: eu-parc/voc2skosmos-workflow/.github/workflows/yml2skos.yml@main
        with:
            ref: ${{ github.ref }}
            namespace: http://www.placeholder.com/
            voc_uri: https://w3id.org/peh/groupings
            linkml_schema: schema/resource.linkml.yml
            data: data/data.yml
            entity_name: Grouping
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}